### PR TITLE
added beards, fixed some bugs around save dir creation

### PR DESCRIPTION
**Pull request by wriley**

### CODE REVIEW

**Comment by wriley** [comment]
Also added save/restore of bloody hands state
Put knife in hands to shave

**Comment by n8m4re** [comment]
hello & welcome wriley, 

thank you, good  work!

**Comment by krakenkoin** [comment]
Awesome teamwork going on here!

**Comment by n8m4re** [comment]
yep this is awesome.

**Comment by Arkensor** [comment]
Great commit, thank you!

**Pull request merged**
